
CREATE TABLE IF NOT EXISTS `rawg_games` (
    `id_rawg` INT,
    `slug` VARCHAR(255),
    `name` VARCHAR(255),
    `released` DATETIME,
    `rating` FLOAT,
    `ratings_count` INT,
    `metacritic` INT,
    `playtime` INT,
    `added` INT,
    `updated` DATETIME,
    `platform_id` TEXT,
    `platform_name` TEXT,
    `platform_slug` TEXT,
    `added_beaten` INT,
    `added_dropped` INT,
    `added_owned` INT,
    `added_playing` INT,
    `added_toplay` INT,
    `added_yet` INT,
    `dw_fecha_registro` DATETIME,
    `dw_id_carga` VARCHAR(36),
    `dw_deleted` BOOLEAN,
    `dw_source` VARCHAR(255),
    `dw_endpoint` TEXT
);

CREATE TABLE IF NOT EXISTS `giantbomb_games` (
    `id_gb` INT AUTO_INCREMENT PRIMARY KEY,
    `guid` VARCHAR(100),
    `name` VARCHAR(255),
    `expected_release_year` INT,
    `original_release_date` DATETIME,
    `date_added` DATETIME,
    `date_last_updated` DATETIME,
    `game_id` INT,
    `platform_id` INT,
    `platform_name` VARCHAR(255),
    `platform_abbr` VARCHAR(50),
    `rating_id` INT,
    `rating_name` VARCHAR(100),
    `dw_fecha_registro` DATETIME,
    `dw_id_carga` VARCHAR(100),
    `dw_deleted` TINYINT,
    `dw_source` VARCHAR(100),
    `dw_endpoint` TEXT
);

CREATE TABLE IF NOT EXISTS `core_pokemon_pokedex` (
    `num` INT,
    `name` VARCHAR(100),
    `tier` VARCHAR(50),
    `heightm` FLOAT,
    `weightkg` FLOAT,
    `color` VARCHAR(50),
    `prevo` VARCHAR(100),
    `evolevel` FLOAT,
    `isnonstandard` VARCHAR(50),
    `cangigantamax` VARCHAR(100),
    `basespecies` VARCHAR(100),
    `forme` VARCHAR(100),
    `requireditem` VARCHAR(100),
    `changesfrom` VARCHAR(100),
    `type_1` VARCHAR(30),
    `type_2` VARCHAR(30),
    `stat_hp` INT,
    `stat_atk` INT,
    `stat_def` INT,
    `stat_spa` INT,
    `stat_spd` INT,
    `stat_spe` INT,
    `ability_0` VARCHAR(100),
    `ability_h` VARCHAR(100),
    `ability_1` VARCHAR(100),
    `ability_s` VARCHAR(100),
    `gender_m` FLOAT,
    `gender_f` FLOAT,
    `gender_0` FLOAT,
    `dw_fecha_registro` DATETIME,
    `dw_id_carga` VARCHAR(100),
    `dw_deleted` TINYINT,
    `dw_source` VARCHAR(100),
    `dw_endpoint` TEXT
);

CREATE TABLE IF NOT EXISTS `core_pokemon_moves` (
    `move_id` INT,
    `num` INT,
    `name` VARCHAR(100),
    `type` VARCHAR(50),
    `category` VARCHAR(50),
    `accuracy` FLOAT,
    `basepower` FLOAT,
    `pp` INT,
    `priority` INT,
    `target` VARCHAR(100),
    `contesttype` VARCHAR(50),
    `recoil` VARCHAR(50),
    `forceswitch` VARCHAR(50),
    `selfdestruct` VARCHAR(50),
    `breaksprotect` VARCHAR(50),
    `ohko` VARCHAR(50),
    `sleepusable` VARCHAR(50),
    `willcrit` VARCHAR(50),
    `flag_allyanim` TINYINT,
    `flag_bite` TINYINT,
    `flag_bullet` TINYINT,
    `flag_bypasssub` TINYINT,
    `flag_cantusetwice` TINYINT,
    `flag_charge` TINYINT,
    `flag_contact` TINYINT,
    `flag_dance` TINYINT,
    `flag_defrost` TINYINT,
    `flag_distance` TINYINT,
    `flag_failcopycat` TINYINT,
    `flag_failencore` TINYINT,
    `flag_failinstruct` TINYINT,
    `flag_failmefirst` TINYINT,
    `flag_failmimic` TINYINT,
    `flag_futuremove` TINYINT,
    `flag_gravity` TINYINT,
    `flag_heal` TINYINT,
    `flag_metronome` TINYINT,
    `flag_mirror` TINYINT,
    `flag_mustpressure` TINYINT,
    `flag_noassist` TINYINT,
    `flag_nonsky` TINYINT,
    `flag_noparentalbond` TINYINT,
    `flag_nosketch` TINYINT,
    `flag_nosleeptalk` TINYINT,
    `flag_pledgecombo` TINYINT,
    `flag_powder` TINYINT,
    `flag_protect` TINYINT,
    `flag_pulse` TINYINT,
    `flag_punch` TINYINT,
    `flag_recharge` TINYINT,
    `flag_reflectable` TINYINT,
    `flag_slicing` TINYINT,
    `flag_snatch` TINYINT,
    `flag_sound` TINYINT,
    `flag_wind` TINYINT,
    `dw_fecha_registro` DATETIME,
    `dw_id_carga` VARCHAR(36),
    `dw_deleted` BOOLEAN,
    `dw_source` VARCHAR(255),
    `dw_endpoint` TEXT
);

CREATE TABLE IF NOT EXISTS `log_operaciones` (
    `fuente` VARCHAR(100),
    `tabla` VARCHAR(100),
    `registros` INT,
    `fecha_inicio` DATETIME,
    `fecha_fin` DATETIME,
    `duracion_segundos` FLOAT,
    `estado` VARCHAR(50),
    `error_msg` TEXT
);

CREATE TABLE IF NOT EXISTS `log_etl_fuentes` (
    `log_time` DATETIME,
    `nivel` VARCHAR(10),
    `fuente` VARCHAR(100),
    `hora_inicio` TIME,
    `hora_fin` TIME,
    `registros` INT,
    `archivo` VARCHAR(100),
    `duracion_segundos` FLOAT,
    `resultado` VARCHAR(20),
    `error` TEXT,
    `mensaje` TEXT
);
